spring:
  profiles: test

  datasource:
    url: jdbc:mysql://mysql:3306/dx_db?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dx111@222

  redis:
    host: redis
    port: 6379

  elasticsearch:
    rest:
      uris: elasticsearch:9200

rpc:
  resource-server: http://127.0.0.1:8081/
  account-server: http://127.0.0.1:8081/

easy:
  data-adapter: jpa
  data: jpa

elasticsearch:
  host: elasticsearch
  port: 9200

minio:
  endpoint: https://a.zsdx.com.cn:9000
  access-key: minio
  secret-key: dx123456
  bucket: dsrd-xzzyy
