server:
  ssl:
    key-store: classpath:9131178_xzzyy.daishan.gov.cn.jks
    key-store-password: q2937e4f
    key-store-type: JKS
    enabled: true

spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://10.25.3.84:3306/zjxz_gwjh?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gwjh
    password: Dx2263!!!

  redis:
    host: redis
    port: 6379
    password: dx2263111

  elasticsearch:
    # username: elastic
    # password: rrqgVK9DGRg43jz1YJkR
    rest:
      uris: elasticsearch:9200

rpc:
  resource-server: http://127.0.0.1:8081/
  account-server: http://127.0.0.1:8081/
  ids-url: "http://60.163.159.240:10001/api/Account/ZFQBi/3V+Dz7SuB4pox3mVDEJPgvGceEucRKNladtng="

security:
  oauth2:
    jwk-url: http://60.163.159.240:10001/.well-known/openid-configuration/jwks

easy:
  data-adapter: jpa
  data: jpa

elasticsearch:
  host: elasticsearch
  port: 9200

minio:
  endpoint: http://minio:9000
  # endpoint: https://a.zsdx.com.cn:9000
  access-key: minio
  secret-key: dx123456
  bucket: zjxz-gwjh

download:
  excel-path: http://60.163.159.240:10002/zjxz-gwjh/files/202310/a57ffbd229ac47d4a0d9eb4f412f5f2f.xlsx
