spring:
  profiles: local

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zjxz_gwjh?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Wangyaodi123@

  redis:
    host: 127.0.0.1
    port: 6379

  elasticsearch:
    rest:
      uris: 127.0.0.1:9200

elasticsearch:
  host: 127.0.0.1
  port: 9200

rpc:
  resource-server: http://127.0.0.1:8081/
  account-server: http://127.0.0.1:8081/

minio:
  endpoint: http://127.0.0.1:9000
  access-key: minio
  secret-key: dx123456
  bucket: dsrd-xzzyy
